allowBuilds:
  esbuild: false
minimumReleaseAgeExclude:
  - '@typescript/typescript-darwin-arm64@7.1.0-dev.20260821.1'
  - '@typescript/typescript-darwin-x64@7.1.0-dev.20260821.1'
  - '@typescript/typescript-linux-arm64@7.1.0-dev.20260821.1'
  - '@typescript/typescript-linux-arm@7.1.0-dev.20260821.1'
  - '@typescript/typescript-linux-x64@7.1.0-dev.20260821.1'
  - '@typescript/typescript-win32-arm64@7.1.0-dev.20260821.1'
  - '@typescript/typescript-win32-x64@7.1.0-dev.20260821.1'
  - typescript@7.1.0-dev.20260821.1
  - '@glint/ember-tsc@1.11.0'
  - ember-estree@0.8.0
packages:
  - '.'
  - examples/*
  - test/test-packages/*
patchedDependencies:
  '@glimmer/syntax@0.95.0': patches/@glimmer__syntax@0.95.0.patch
  mitata@1.0.34: patches/mitata@1.0.34.patch
